elasticsearch:
  build: ./elasticsearch
  ports:
    - "9200:9200"
    - "9300:9300"

kibana:
  build: ./kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch

logstash:
  build: ./logstash
  ports:
    - "8080:8080"
  links:
    - elasticsearch
