elasticsearch:
  build: ./elasticsearch

kibana:
  build: ./kibana
  ports:
    - "5601:5601"
  links:
    - elasticsearch

logstash:
  build: ./logstash
  ports:
    - "8080:8080"
  links:
    - elasticsearch
